# Copyright 2016 CampaignChain, Inc. <info@campaignchain.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sp_bower:
    bundles:
        CampaignChainAutocompleteFormTypeBundle:
            cache: %kernel.cache_dir%/../bower
            asset_dir: %kernel.root_dir%/../web/vendor/campaignchain/form-type-autocomplete

assetic:
    bundles:
        - CampaignChainAutocompleteFormTypeBundle
    assets:
        at_css:
            inputs:
                - "%kernel.root_dir%/../web/vendor/campaignchain/form-type-autocomplete/jquery.atwho/dist/css/jquery.atwho.min.css"
                - "@CampaignChainAutocompleteFormTypeBundle/Resources/public/css/base.css"
        at_js:
            inputs:
                - "%kernel.root_dir%/../web/vendor/campaignchain/form-type-autocomplete/Caret.js/dist/jquery.caret.min.js"
                - "%kernel.root_dir%/../web/vendor/campaignchain/form-type-autocomplete/jquery.atwho/dist/js/jquery.atwho.min.js"

twig:
    form_themes:
        - 'CampaignChainAutocompleteFormTypeBundle:Form:fields.html.twig'